apiVersion: apps/v1
kind: Deployment
metadata:
    name: time
spec:
    selector:
        matchLabels:
            app: time
    template:
        metadata:
            labels:
                app: time
        spec:
            containers:
            - name: time
              image: abuosi/time:1.0
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: time
spec:
    selector:
        app: time
    ports:
    - port: 8080
      targetPort: 8080